version: "3.7"
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env.local
    environment:
      - PORT=5000
      - CHROME_EXECUTABLE_PATH=/usr/bin/chromium-browser
    ports:
      - 5000:5000